services:
  db:
    image: mysql:8.0
    container_name: shu2dwi-cur-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cursos
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3307:3306"  
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d  

  web:
    build: .
    container_name: shu2dwi-cur-web
    depends_on:
      - db
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    environment:
      MYSQL_HOST: db          
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      MYSQL_DATABASE: cursos

volumes:
  db_data:
